/**
 * Created by bear on 2017/12/26.
 */
export const messageTypes = {
  MSG_REQUEST_LIST: 'MSG_REQUEST_LIST',
  MSG_RECEIVE_LIST: 'MSG_RECEIVE_LIST'
};

export const authTypes = {
  USER_LOGIN: 'USER_LOGIN',
  USER_REG: 'USER_REG',
  USER_MODIFY: 'USER_MODIFY',
  USER_PROFILE: 'USER_PROFILE',
  USER_CHANGE_PASSWORD: 'USER_CHANGE_PASSWORD'
};

export const contactTypes = {
  REQUEST_CST_LIST: 'REQUEST_CST_LIST',
  RECEIVE_CST_LIST: 'RECEIVE_CST_LIST',
  RECORD_SECTION: 'RECORD_SECTION'
};
export const applicationTypes = {
  REQUEST_GRID_LIST: 'REQUEST_GRID_LIST',
  RECEIVE_GRID_LIST: 'RECEIVE_GRID_LIST'
};
export const socketTypes = {
  SOCKET_CONNECTION: 'SOCKET_CONNECTION',
  SOCKET_CONNECTION_FAIL: 'SOCKET_CONNECTION_FAIL',
  SOCKET_DISCONNECTION: 'SOCKET_DISCONNECTION',
  SOCKET_EMIT_MESSAGE: 'SOCKET_EMIT_MESSAGE',
  SOCKET_ON_MESSAGE: 'SOCKET_ON_MESSAGE',
  SOCKET_SAVE_CURRENT_CHAT_KEY: 'SOCKET_SAVE_CURRENT_CHAT_KEY',
  SOCKET_DEL_CURRENT_CHAT_KEY: 'SOCKET_DEL_CURRENT_CHAT_KEY',
  SOCKET_CURRENT_HISTORY: 'SOCKET_CURRENT_HISTORY',
  SESSION_SAVE_TO_LOCAL: 'SESSION_SAVE_TO_LOCAL',
  SESSION_RESTORE: 'SESSION_RESTORE'
};
export const dynamicTypes = {
  REQUEST_TOPICS_LIST: 'REQUEST_TOPICS_LIST',
  RECEIVE_TOPICS_LIST: 'RECEIVE_TOPICS_LIST',
  GET_ARTICLE_DETAIL: 'GET_ARTICLE_DETAIL'
};

export const carTypes = {

  //二手车
  REQUEST_OLD_CAR_LIST: 'REQUEST_OLD_CAR_LIST',
  RECEIVE_OLD_CAR_LIST: 'RECEIVE_OLD_CAR_LIST',
  //新车
  REQUEST_NEW_CAR_LIST: 'REQUEST_NEW_CAR_LIST',
  RECEIVE_NEW_CAR_LIST: 'RECEIVE_NEW_CAR_LIST',
  //事故车
  REQUEST_DAMAGE_CAR_LIST: 'REQUEST_DAMAGE_CAR_LIST',
  RECEIVE_DAMAGE_CAR_LIST: 'RECEIVE_DAMAGE_CAR_LIST',
  //会员点击榜
  REQUEST_USER_CLICK_CAR_LIST: 'REQUEST_USER_CLICK_CAR_LIST',
  RECEIVE_USER_CLICK_CAR_LIST: 'RECEIVE_USER_CLICK_CAR_LIST',
  //人气下载榜
  REQUEST_USER_DOWNLOAD_CAR_LIST: 'REQUEST_USER_DOWNLOAD_CAR_LIST',
  RECEIVE_USER_DOWNLOAD_CAR_LIST: 'RECEIVE_USER_DOWNLOAD_CAR_LIST',


  REQUEST_CAR_DETAIL: 'REQUEST_CAR_DETAIL',
  RECEIVE_CAR_DETAIL: 'RECEIVE_CAR_DETAIL',
}
export const carBrandTypes = {
  //品牌
  REQUEST_CAR_BRAND_LIST: 'REQUEST_CAR_BRAND_LIST',
  RECEIVE_CAR_BRAND_LIST: 'RECEIVE_CAR_BRAND_LIST',
  //车系
  REQUEST_CAR_SERIES_LIST: 'REQUEST_CAR_SERIES_LIST',
  RECEIVE_CAR_SERIES_LIST: 'RECEIVE_CAR_SERIES_LIST',
  //车型
  REQUEST_CAR_MODEL_LIST: 'REQUEST_CAR_MODEL_LIST',
  RECEIVE_CAR_MODEL_LIST: 'RECEIVE_CAR_MODEL_LIST',



}